### ISSUE TITLE
Features to support MangoTube, MangoTube8 and MangoTube Legacy (listed below):

### ISSUE THREAD

**Issue by SGR21gtb** [erievs/mangotube#3]
- Captions (auto-generated and by user)
- LIVE! videos and chats (there would be a separate tab called live chat next to comments)
- Annotations (will be shown in bottom of description)
- Profile pictures in description, related videos, comments and live chat
- Themes (with pre-made YouTube-like theme for MangoTube8)
- Rest of account-related features (favorites/playlists, subscribing/subscriptions, uploading/uploads, watch and search history etc.)
- TV support (casting, remote, pairing)
- Probably a desktop version of MangoTube8

**Comment by erievs** [comment]
Not taking feature requests

**Comment by erievs** [comment]
These aren't issues and are way too much work

**Comment by SGR21gtb** [comment]
> These aren't issues and are way too much work

when you will start on this ?

**Comment by SGR21gtb** [comment]
> Not taking feature requests

oh

**Comment by SGR21gtb** [comment]
sorry

**Comment by erievs** [comment]
> > These aren't issues and are way too much work
> 
> when you will start on this ?

Never

Please never post feature requests here again.
